<?php

return array(
    'title' => 'Webmypham',
    'pretitle' => '',
    'suftitle' => '- WebMyPham - Chuyên cung cấp sỉ và lẻ mỹ phẩm Hàn Quốc - Thailand  - USA',
    'description' => 'Thái Boutique - Webmypham - Chuyên sỉ và lẻ mỹ phẩm Hàn Quốc, Thai lan, USA - Kem trắng da - Trị mụn - son - trang điểm',
    'keywords'  => 'mỹ phẩm, my pham, thai lan, thailan, the face shop, kem trắng da, kem trị mụn, kem mọc tóc, white, skin, beauty, spa, laila, mood matcher, wet n wild, nyx, revlon, kem dna ',
    'treecatdeep' => 1,
    'tablepp'    =>  18,
    'theme' => 'default',
    'topnav' => array(
        'home' => array(
            'id' => 'home',
            'url' => '/',
            'title' => 'Trang chủ',
            'icon' => 'glyphicon glyphicon-home',
        ),
        'new' => array(
            'id' => 'new',
            'url' => '/fav/new-arrived',
            'title' => 'Hàng mới về',
            'icon' => 'glyphicon glyphicon-star',
        ),
        'hot' => array(
            'id' => 'hot',
            'url' => '/fav/hot-product',
            'title' => 'Hàng đang hot',
            'icon' => 'glyphicon glyphicon-thumbs-up',
        ),
        'sale' => array(
            'id' => 'sale',
            'url' => '/fav/sale-product',
            'title' => 'Hàng khuyến mãi',
            'icon' => 'glyphicon glyphicon-gift',
        ),
    ),
    'shipping' => array(
        'ship_shop' => array(
            'id' => 'ship_shop',
            'value' => 'Nhận  tại cửa hàng',
            'time' => '1',
            'pay_allow' => '',
            'province_allow' => 'hcm',
        ),
        'ship_hcm' => array(
            'id' => 'ship_hcm',
            'value' => 'Ship Nội thành Sài Gòn',
            'time' => '1~2',
            'pay_allow' => '',
            'province_allow' => 'hcm',
        ),
        'ship_xe' => array(
            'id' => 'ship_xe',
            'value' => 'Gửi nhà xe',
            'time' => '1~2',
            'pay_allow' => '',
            'province_allow' => '',
        ),
        'ship_postnhanh' => array(
            'id' => 'ship_postnhanh',
            'value' => 'Gửi Chuyển phát nhanh',
            'time' => '1~2',
            'pay_allow' => '',
            'province_allow' => '',
        ),
        'ship_post' => array(
            'id' => 'ship_post',
            'value' => 'Gửi bưu phẩm',
            'time' => '5~7',
            'pay_allow' => '',
            'province_allow' => '',
        ),
    ),
    'payment' => array(
        'pay_tienmat' => array(
            'id' => 'pay_tienmat',
            'value' => 'Tiền mặt',
        ),
        'pay_chuyenkhoan' => array(
            'id' => 'pay_chuyenkhoan',
            'value' => 'Chuyển khoản ngân hàng',
        ),
        'pay_cod' => array(
            'id' => 'pay_cod',
            'value' => 'COD (thanh toán khi nhận bưu phẩm)',
        ),
    ),
    'province' => array(
        'hcm' => array( 'id' => 'hcm','title' =>'TP Hồ Chí Minh' ,'group' => 0,'guixe'=>'0'),
        'hanoi' => array( 'id' => 'hanoi','title' =>'Hà Nội' ,'group' => 1,'guixe'=>'0'),
        'danang' => array( 'id' => 'danang','title' =>'Đà Nẵng' ,'group' => 2,'guixe'=>'0'),
        'angiang' => array( 'id' => 'angiang','title' =>'An Giang' ,'group' => 3,'guixe'=>'0'),
        'binhduong' => array( 'id' => 'binhduong','title' =>'Bình Dương ' ,'group' => 3,'guixe'=>'0'),
        'binhphuoc' => array( 'id' => 'binhphuoc','title' =>'Bình Phước ' ,'group' => 3,'guixe'=>'0'),
        'vungtau' => array( 'id' => 'vungtau','title' =>'Bà Rịa - Vũng Tàu' ,'group' => 3,'guixe'=>'0'),
        'baclieu' => array( 'id' => 'baclieu','title' =>'Bạc Liêu' ,'group' => 3,'guixe'=>'0'),
        'bentre' => array( 'id' => 'bentre','title' =>'Bến Tre' ,'group' => 3,'guixe'=>'0'),
        'binhthuan' => array( 'id' => 'binhthuan','title' =>'Bình Thuận ' ,'group' => 3,'guixe'=>'0'),
        'camau' => array( 'id' => 'camau','title' =>'Càu Mau' ,'group' => 3,'guixe'=>'0'),
        'cantho' => array( 'id' => 'cantho','title' =>'Cần Thơ' ,'group' => 3,'guixe'=>'0'),
        'dongnai' => array( 'id' => 'dongnai','title' =>'Đồng Nai' ,'group' => 3,'guixe'=>'0'),
        'dongthap' => array( 'id' => 'dongthap','title' =>'Đồng Tháp' ,'group' => 3,'guixe'=>'0'),
        'haugiang' => array( 'id' => 'haugiang','title' =>'Hậu Giang' ,'group' => 3,'guixe'=>'0'),
        'kiengiang' => array( 'id' => 'kiengiang','title' =>'Kiên Giang' ,'group' => 3,'guixe'=>'0'),
        'longan' => array( 'id' => 'longan','title' =>'Long An' ,'group' => 3,'guixe'=>'0'),
        'lamdong' => array( 'id' => 'lamdong','title' =>'Lâm Đồng' ,'group' => 3,'guixe'=>'0'),
        'ninhthuan' => array( 'id' => 'ninhthuan','title' =>'Ninh Thuận' ,'group' => 3,'guixe'=>'0'),
        'soctrang' => array( 'id' => 'soctrang','title' =>'Sóc Trăng' ,'group' => 3,'guixe'=>'0'),
        'tayninh' => array( 'id' => 'tayninh','title' =>'Tây Ninh ' ,'group' => 3,'guixe'=>'0'),
        'tiengiang' => array( 'id' => 'tiengiang','title' =>'Tiền Giang ' ,'group' => 3,'guixe'=>'0'),
        'travinh' => array( 'id' => 'travinh','title' =>'Trà Vinh' ,'group' => 3,'guixe'=>'0'),
        'vinhlong' => array( 'id' => 'vinhlong','title' =>'Vĩnh Long' ,'group' => 3,'guixe'=>'0'),
        'daklak' => array( 'id' => 'daklak','title' =>'DakLak' ,'group' => 3,'guixe'=>'0'),
        'daknong' => array( 'id' => 'daknong','title' =>'DakNong' ,'group' => 3,'guixe'=>'0'),
        'binhdinh' => array( 'id' => 'binhdinh','title' =>'Bình Định' ,'group' => 4,'guixe'=>'0'),
        'gialai' => array( 'id' => 'gialai','title' =>'Gia Lai' ,'group' => 4,'guixe'=>'0'),
        'hue' => array( 'id' => 'hue','title' =>'Thừa Thiên Huế' ,'group' => 4,'guixe'=>'0'),
        'komtum' => array( 'id' => 'komtum','title' =>'Kom Tum' ,'group' => 4,'guixe'=>'0'),
        'khanhhoa' => array( 'id' => 'khanhhoa','title' =>'Khánh Hòa' ,'group' => 4,'guixe'=>'0'),
        'phuyen' => array( 'id' => 'phuyen','title' =>'Phú Yên' ,'group' => 4,'guixe'=>'0'),
        'quangbinh' => array( 'id' => 'quangbinh','title' =>'Quảng Bình' ,'group' => 4,'guixe'=>'0'),
        'quangtri' => array( 'id' => 'quangtri','title' =>'Quảng Trị' ,'group' => 4,'guixe'=>'0'),
        'quangnam' => array( 'id' => 'quangnam','title' =>'Quảng Nam' ,'group' => 4,'guixe'=>'0'),
        'quangngai' => array( 'id' => 'quangngai','title' =>'Quảng Ngãi' ,'group' => 4,'guixe'=>'0'),
        'baccan' => array( 'id' => 'baccan','title' =>'Bắc Cạn' ,'group' => 4,'guixe'=>'0'),
        'bacgiang' => array( 'id' => 'bacgiang','title' =>'Bắc Giang' ,'group' => 4,'guixe'=>'0'),
        'bacninh' => array( 'id' => 'bacninh','title' =>'Bắc Ninh' ,'group' => 4,'guixe'=>'0'),
        'caobang' => array( 'id' => 'caobang','title' =>'Cao Bằng' ,'group' => 4,'guixe'=>'0'),
        'dienbien' => array( 'id' => 'dienbien','title' =>'Điện Biên' ,'group' => 4,'guixe'=>'0'),
        'hagiang' => array( 'id' => 'hagiang','title' =>'Hà Giang' ,'group' => 4,'guixe'=>'0'),
        'hanam' => array( 'id' => 'hanam','title' =>'Hà Nam' ,'group' => 4,'guixe'=>'0'),
        'hatinh' => array( 'id' => 'hatinh','title' =>'Hà Tĩnh' ,'group' => 4,'guixe'=>'0'),
        'hungyen' => array( 'id' => 'hungyen','title' =>'Hưng Yên' ,'group' => 4,'guixe'=>'0'),
        'hoabinh' => array( 'id' => 'hoabinh','title' =>'Hòa Bình' ,'group' => 4,'guixe'=>'0'),
        'laocai' => array( 'id' => 'laocai','title' =>'Lào Cai' ,'group' => 4,'guixe'=>'0'),
        'laichau' => array( 'id' => 'laichau','title' =>'Lai Châu' ,'group' => 4,'guixe'=>'0'),
        'langson' => array( 'id' => 'langson','title' =>'Lạng Sơn' ,'group' => 4,'guixe'=>'0'),
        'namdinh' => array( 'id' => 'namdinh','title' =>'Nam Định' ,'group' => 4,'guixe'=>'0'),
        'nghean' => array( 'id' => 'nghean','title' =>'Nghệ An' ,'group' => 4,'guixe'=>'0'),
        'ninhbinh' => array( 'id' => 'ninhbinh','title' =>'Ninh Bình' ,'group' => 4,'guixe'=>'0'),
        'phutho' => array( 'id' => 'phutho','title' =>'Phú Thọ' ,'group' => 4,'guixe'=>'0'),
        'sonla' => array( 'id' => 'sonla','title' =>'Sơn La' ,'group' => 4,'guixe'=>'0'),
        'thaibinh' => array( 'id' => 'thaibinh','title' =>'Thái Bình' ,'group' => 4,'guixe'=>'0'),
        'thainguyen' => array( 'id' => 'thainguyen','title' =>'Thái Nguyên' ,'group' => 4,'guixe'=>'0'),
        'thanhhoa' => array( 'id' => 'thanhhoa','title' =>'Thanh Hóa' ,'group' => 4,'guixe'=>'0'),
        'tuyenquang' => array( 'id' => 'tuyenquang','title' =>'Tuyên Quang' ,'group' => 4,'guixe'=>'0'),
        'yenbai' => array( 'id' => 'yenbai','title' =>'Yên Bái' ,'group' => 4,'guixe'=>'0'),
        'haiduong' => array( 'id' => 'haiduong','title' =>'Hải Dương' ,'group' => 4,'guixe'=>'0'),
        'haiphong' => array( 'id' => 'haiphong','title' =>'Hải Phòng' ,'group' => 4,'guixe'=>'0'),
        'quangninh' => array( 'id' => 'quangninh','title' =>'Quảng Ninh' ,'group' => 4,'guixe'=>'0'),
        'vinhphuc' => array( 'id' => 'vinhphuc','title' =>'Vĩnh Phúc' ,'group' => 4,'guixe'=>'0'),

    ),
    'emsprice' => array(
        '50' => array('klg'=>50,'g1a'=>12540,'g1b'=>14630,'g2a'=>12540,'g2b'=>14630,'g3a'=> 11220,'g3b'=> 13090,'g4a'=> 13200,'g4b'=> 15400),
        '100' => array('klg'=>100,'g1a'=>17820,'g1b'=>20790,'g2a'=>17820,'g2b'=>20790,'g3a'=> 16500,'g3b'=> 19250,'g4a'=> 18480,'g4b'=> 21560),
        '250' => array('klg'=>250,'g1a'=>28380,'g1b'=>33110,'g2a'=>26400,'g2b'=>30800,'g3a'=> 21780,'g3b'=> 25410,'g4a'=> 29700,'g4b'=> 34650),
        '500' => array('klg'=>500,'g1a'=>36960,'g1b'=>43120,'g2a'=>34980,'g2b'=>40810,'g3a'=> 31020,'g3b'=> 36190,'g4a'=> 38940,'g4b'=> 45430),
        '1000' => array('klg'=>1000,'g1a'=>53460,'g1b'=>62370,'g2a'=>50820,'g2b'=>59290,'g3a'=> 43560,'g3b'=> 50820,'g4a'=> 57420,'g4b'=> 66990),
        '1500' => array('klg'=>1500,'g1a'=>69300,'g1b'=>80850,'g2a'=>65340,'g2b'=>76230,'g3a'=> 52800,'g3b'=> 61600,'g4a'=> 73260,'g4b'=> 85470),
        '2000' => array('klg'=>2000,'g1a'=>83820,'g1b'=>97790,'g2a'=>78540,'g2b'=>91630,'g3a'=> 64020,'g3b'=> 74690,'g4a'=> 89100,'g4b'=> 103950),
        '2500' => array('klg'=>2500,'g1a'=>95040,'g1b'=>110880,'g2a'=>89760,'g2b'=>104720,'g3a'=> 69036,'g3b'=> 80542,'g4a'=> 101640,'g4b'=> 118580),
        '3000' => array('klg'=>3000,'g1a'=>106260,'g1b'=>123970,'g2a'=>100980,'g2b'=>117810,'g3a'=> 74052,'g3b'=> 86394,'g4a'=> 114180,'g4b'=> 133210),
        '3500' => array('klg'=>3500,'g1a'=>117480,'g1b'=>137060,'g2a'=>112200,'g2b'=>130900,'g3a'=> 79068,'g3b'=> 92246,'g4a'=> 126720,'g4b'=> 147840),
        '4000' => array('klg'=>4000,'g1a'=>128700,'g1b'=>150150,'g2a'=>123420,'g2b'=>143990,'g3a'=> 84084,'g3b'=> 98098,'g4a'=> 139260,'g4b'=> 162470),
        '4500' => array('klg'=>4500,'g1a'=>139920,'g1b'=>163240,'g2a'=>134640,'g2b'=>157080,'g3a'=> 89100,'g3b'=> 103950,'g4a'=> 151800,'g4b'=> 177100),
        '5000' => array('klg'=>5000,'g1a'=>151140,'g1b'=>176330,'g2a'=>145860,'g2b'=>170170,'g3a'=> 94116,'g3b'=> 109802,'g4a'=> 164340,'g4b'=> 191730),
        'more' => array('klg'=>500,'g1a'=>11220,'g1b'=>13090,'g2a'=>11220,'g2b'=>13090,'g3a'=> 5016,'g3b'=> 5852,'g4a'=> 12540,'g4b'=> 14630),
    ),
);